name: dartresttest
description: A new Flutter project.
version: 0.0.1

publish_to: 'none'

environment:
  sdk: '^3.3.0'

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  chopper_generator: ^6.0.0

dependencies:
  swagger_dart_code_generator: ^2.15.2
  chopper: ^6.1.4
  collection: ^1.18.0
  json_annotation: ^4.9.0
  dio: ^5.4.3+1
